title = "MyPaint"
baseURL = 'https://mypaint.org/'
languageCode = 'en'

contentDir = 'pages'

[params]
siteDescription = """
MyPaint is an easy-to-use painting program which works well with Wacom graphics tablets and other similar devices. \
It comes with a large brush collection including charcoal and ink to emulate real media, \
but the highly configurable brush engine allows you to experiment with your own brushes and with not-quite-natural painting.
"""
siteKeywords = "application, art, drawing, FOSS, software"
#mainSections = ['food','music','society','technology']

[markup]
[markup.tableOfContents]
startLevel = 1
